Repository xBlue0/lifeatde-app, pull requests merged in 2018-11, with the labels that each got.

#9 Anteprima foto libro nella Card
  src/components/BookCard.js
  src/img/image-placeholder.jpg
Labels: enhancement

#10 Gruppo di studio
  src/App.js
  src/components/StudyGroup.js
  src/components/StudyGroupCard.js
  src/containers/AppContainer.js
  src/containers/NewsCardsContainer.js
  src/containers/StudyGroupContainer.js
  src/lib/Utils.js
Labels: enhancement

#13 Refactor struttura:
  src/App.js
  src/components/books/BookCard.js
  src/components/books/BookCardList.js
  src/components/common/Footer.js
  src/components/common/Loader.js
  src/components/common/NoMatch.js
  src/components/common/Notifier.js
  src/components/common/PrivateRoute.js
  src/components/common/RailsIcon.js
  src/components/common/TeamModal.js
  src/components/common/ThemeWrapper.js
  src/components/news/NewsCard.js
  src/components/news/NewsCardList.js
  src/components/projects/CategoriesMenu.js
  src/components/projects/DocumentList.js
  src/components/projects/Project.js
  src/components/projects/ProjectCard.js
  src/components/projects/ProjectCardList.js
  src/components/projects/ProjectTeam.js
  src/components/study-groups/StudyGroup.js
  src/components/study-groups/StudyGroupCard.js
  src/components/study-groups/StudyGroupCardList.js
  src/containers/BookCardsContainer.js
  src/containers/Login.js
  src/containers/NewsCardsContainer.js
  src/containers/ProjectCardsContainer.js
  src/containers/ProjectContainer.js
  src/containers/SearchContainer.js
  src/containers/StudyGroupCardsContainer.js
  src/containers/StudyGroupContainer.js
  src/index.js
  src/lib/Api.js
  src/lib/Utils.js
Labels: enhancement

#15 Migliorata la visualizzazione delle foto nelle card dei libri
  src/components/books/BookCard.js
  src/components/common/Anchor.js
  src/components/projects/CategoriesMenu.js
  src/components/projects/DocumentList.js
  src/components/projects/Project.js
  src/components/projects/ProjectCard.js
  src/components/study-groups/StudyGroupCard.js
  src/containers/BookCardsContainer.js
  src/containers/StudyGroupContainer.js
  src/lib/Api.js
  src/lib/Utils.js
Labels: enhancement

#16 Anchor fix
  src/components/projects/ProjectTeam.js
  src/components/study-groups/StudyGroup.js
  src/lib/Utils.js
Labels: fix

#19 Refactor DRY
  src/components/books/Book.js
  src/components/books/BookCard.js
  src/components/books/BookCardList.js
  src/components/common/DeleteConfirmationDialog.js
  src/components/common/EditDeleteActions.js
  src/components/projects/FileList.js
  src/components/projects/Project.js
  src/components/projects/ProjectCard.js
  src/components/study-groups/StudyGroup.js
  src/components/study-groups/StudyGroupCard.js
  src/components/study-groups/StudyGroupCardList.js
  src/containers/BookCardsContainer.js
  src/containers/NewsCardsContainer.js
  src/containers/ProjectCardsContainer.js
  src/containers/StudyGroupCardsContainer.js
  src/containers/StudyGroupContainer.js
Labels: enhancement

#22 Profilo utente:
  src/App.js
  src/components/common/AsyncAvatar.js
  src/components/common/Autocomplete.js
  src/components/projects/ProjectCard.js
  src/components/projects/ProjectCardList.js
  src/components/projects/ProjectForm.js
  src/components/user/Tabs.js
  src/containers/AppContainer.js
  src/containers/BookContainer.js
  src/containers/Login.js
  src/containers/SearchContainer.js
  src/containers/UserProfile.js
  src/lib/Api.js
  src/lib/Authentication.js
  src/lib/Utils.js
Labels: enhancement

#23 Study group form
  src/App.js
  src/components/news/NewsCard.js
  src/components/study-groups/StudyGroup.js
  src/components/study-groups/StudyGroupForm.js
  src/containers/StudyGroupCardsContainer.js
  src/containers/StudyGroupEditContainer.js
  src/containers/StudyGroupNewContainer.js
Labels: enhancement

#24 Uniformati tutti gli avatar con AsyncAvatar
  src/components/books/BookCard.js
  src/components/projects/ProjectCard.js
  src/components/projects/ProjectTeam.js
  src/components/study-groups/StudyGroup.js
  src/components/study-groups/StudyGroupCard.js
  src/containers/AppContainer.js
Labels: fix

#27 Speed Dial:
  package.json
  src/components/common/SpeedDials.js
  src/components/projects/ProjectForm.js
  src/components/study-groups/StudyGroupForm.js
  src/containers/AppContainer.js
  yarn.lock
Labels: enhancement

#25 Ricerca Utenti
  src/components/study-groups/StudyGroupCard.js
  src/components/user/UserCard.js
  src/components/user/UserCardList.js
  src/containers/SearchContainer.js
Labels: enhancement

#28 Bugfixing
  src/components/books/BookCard.js
  src/components/books/PriceChip.js
  src/components/common/Autocomplete.js
  src/components/projects/ProjectCard.js
  src/components/study-groups/StudyGroupCard.js
  src/components/user/Tabs.js
  src/containers/BookCardsContainer.js
  src/containers/ProjectCardsContainer.js
  src/containers/StudyGroupCardsContainer.js
  src/containers/UserProfile.js
Labels: fix

#30 Load more:
  src/components/books/BookCardList.js
  src/components/common/LoadMoreButton.js
  src/components/filters/ProjectFilters.js
  src/components/study-groups/StudyGroupCardList.js
  src/components/user/Tabs.js
  src/components/user/UserCardList.js
  src/containers/BookCardsContainer.js
  src/containers/ProjectCardsContainer.js
  src/containers/SearchContainer.js
  src/containers/StudyGroupCardsContainer.js
Labels: enhancement

#33 Ui enhanchment
  src/components/books/Book.js
  src/components/books/BookCard.js
  src/components/books/BookForm.js
  src/components/filters/ProjectFilters.js
  src/components/projects/Project.js
  src/components/projects/ProjectForm.js
  src/components/study-groups/StudyGroup.js
  src/components/study-groups/StudyGroupForm.js
  src/containers/BookCardsContainer.js
  src/containers/ProjectCardsContainer.js
  src/containers/SearchContainer.js
  src/containers/StudyGroupCardsContainer.js
  src/containers/UserProfile.js
Labels: enhancement, fix

#34 Aggiunti i filtri per i books
  src/components/filters/BooksFilters.js
  src/components/filters/CourseFilter.js
  src/components/filters/ProjectFilters.js
  src/containers/BookCardsContainer.js
  src/containers/StudyGroupCardsContainer.js
Labels: enhancement
